name: "text_renderer_gpu"
backend: "text_renderer_gpu"
max_batch_size: 16

dynamic_batching {
  preferred_batch_size: [ 4, 8, 16 ]
  max_queue_delay_microseconds: 2000
}

input [
  {
    name: "input_images"
    data_type: TYPE_UINT8
    dims: [ 1200, 900, 3 ]
  },
  {
    name: "command_version"
    data_type: TYPE_INT32
    dims: [ 1 ]
  },
  {
    name: "command_bytes"
    data_type: TYPE_UINT8
    dims: [ -1 ]
    allow_ragged_batch: true
  },
  {
    name: "batch_bytes"
    data_type: TYPE_UINT8
    dims: [ -1 ]
    allow_ragged_batch: true
  }
]

output [
  {
    name: "rendered_image"
    data_type: TYPE_UINT8
    dims: [ 1200, 900, 3 ]
  }
]

instance_group [
  {
    kind: KIND_GPU
    count: 1
  }
]
